server:
  port: 8080

# SSH 터널 활성화
ssh:
  enabled: true
  host: 49.50.133.13
  sshPort: 22
  username: as_evse
  password: asEvse!1@2
  localPort: 3306
  remoteHost: localhost  # 원격 MySQL이 SSH 서버와 같은 머신에 있는 경우
  remotePort: 3306

#java -jar .\SCSystem-SNAPSHOT.jar --spring.profiles.active=dev
spring:
  jmx:
    enabled: false
  # 어플리케이션
  application:
    name: SCSystem
  # DB 연결 정보
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/as_evse
    username: as_evse
    password: asEvse!1@2

file:
  upload:
    path: C:/uploads/
  template:
    path: C:/dev/project/
  
    
# MyBatis 설정 정보
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.SCSystem
  
logging:
  level:
    root: info